theme = "everforest_dark"

[editor]
line-number = "relative"
auto-pairs = false

[editor.soft-wrap]
enable = true

[keys.normal]
"C-j" = "half_page_down"
"C-k" = "half_page_up"
"C-h" = "goto_line_start"
"C-l" = "goto_line_end"

[keys.insert]
"C-[" = "normal_mode"
