[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.pyright]
command = "pyright"
args = ["server"]

[language-server.ty]
command = "ty"
args = ["server"]

[[language]]
name = "python"
language-servers = ["ruff", "ty", "pylsp"]
auto-format = true

indent = { tab-width = 4, unit = " " }
